# Generated by Django 4.0.4 on 2022-05-24 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_editor_phone_number_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.editor'),
            preserve_default=False,
        ),
    ]
